export type SchemaIndex = {
  name: string;
  table: string;
  columns: string[];
  unique?: boolean;
  where?: string;
};

export const SCHEMA_INDEXES: SchemaIndex[] = [
  { name: 'idx_topic_search_cache_key', table: 'topic_search_cache', columns: ['cache_key'], unique: true },
  { name: 'idx_topic_search_cache_expires', table: 'topic_search_cache', columns: ['expires_at'] },
  { name: 'idx_scheduled_posts_status_time', table: 'scheduled_posts', columns: ['status', 'scheduled_time'] },
  { name: 'idx_scheduled_posts_account_status_time', table: 'scheduled_posts', columns: ['account_slot', 'status', 'scheduled_time'] },
  { name: 'idx_x_accounts_slot', table: 'x_accounts', columns: ['slot'], unique: true },
  { name: 'idx_app_settings_key', table: 'app_settings', columns: ['setting_key'], unique: true },
  { name: 'idx_scheduler_locks_key', table: 'scheduler_locks', columns: ['lock_key'], unique: true },
  { name: 'idx_engagement_inbox_source', table: 'engagement_inbox', columns: ['account_slot', 'source_type', 'source_id'], unique: true },
  { name: 'idx_engagement_inbox_status', table: 'engagement_inbox', columns: ['account_slot', 'status', 'received_at'] },
  { name: 'idx_engagement_actions_created', table: 'engagement_actions', columns: ['account_slot', 'created_at'] },
  { name: 'idx_campaigns_status', table: 'campaigns', columns: ['account_slot', 'status', 'start_at', 'end_at'] },
  { name: 'idx_campaign_tasks_campaign', table: 'campaign_tasks', columns: ['campaign_id', 'status', 'due_at'] },
  { name: 'idx_campaign_approvals_status', table: 'campaign_approvals', columns: ['campaign_id', 'status', 'requested_at'] },
  { name: 'idx_api_idempotency_scope_key', table: 'api_idempotency', columns: ['scope', 'idempotency_key'], unique: true },
  { name: 'idx_api_idempotency_expires', table: 'api_idempotency', columns: ['expires_at'] },
  { name: 'idx_agent_runs_campaign', table: 'agent_runs', columns: ['campaign_id', 'status', 'started_at'] },
  { name: 'idx_agent_run_steps_run', table: 'agent_run_steps', columns: ['run_id', 'started_at'] },
  { name: 'idx_scheduled_actions_status_time', table: 'scheduled_actions', columns: ['status', 'scheduled_time'] },
  { name: 'idx_scheduled_actions_account', table: 'scheduled_actions', columns: ['account_slot', 'status', 'scheduled_time'] },
  { name: 'idx_x_api_calls_slot_created', table: 'x_api_calls', columns: ['account_slot', 'created_at'] },
  { name: 'idx_engagement_cursors_slot_type', table: 'engagement_cursors', columns: ['account_slot', 'cursor_type'], unique: true },
  { name: 'idx_inbox_tags_inbox', table: 'inbox_tags', columns: ['inbox_id'] },
  { name: 'idx_inbox_tags_unique', table: 'inbox_tags', columns: ['inbox_id', 'tag'], unique: true },
  { name: 'idx_inbox_notes_inbox', table: 'inbox_notes', columns: ['inbox_id'] },
  { name: 'idx_draft_posts_account', table: 'draft_posts', columns: ['account_slot', 'created_at'] },
  { name: 'idx_post_metrics_twitter_id', table: 'post_metrics', columns: ['twitter_post_id'] },
  { name: 'idx_post_metrics_scheduled_post', table: 'post_metrics', columns: ['scheduled_post_id', 'fetched_at'] },
  { name: 'idx_post_metrics_slot_fetched', table: 'post_metrics', columns: ['account_slot', 'fetched_at'] },
  { name: 'idx_content_queue_slot_status', table: 'content_queue', columns: ['account_slot', 'status', 'position'] },
  { name: 'idx_agent_webhooks_active', table: 'agent_webhooks', columns: ['active'] },
  { name: 'idx_events_type_created', table: 'events', columns: ['event_type', 'created_at'] },
  { name: 'idx_events_entity', table: 'events', columns: ['entity_type', 'entity_id'] },
  { name: 'idx_events_unread', table: 'events', columns: ['read_at', 'created_at'], where: 'read_at IS NULL' },
  { name: 'idx_webhook_deliveries_webhook', table: 'webhook_deliveries', columns: ['webhook_id', 'created_at'] },
  { name: 'idx_webhook_deliveries_event', table: 'webhook_deliveries', columns: ['event_id'] },
  { name: 'idx_media_library_mime', table: 'media_library', columns: ['mime_type'] },
  { name: 'idx_media_library_uploaded', table: 'media_library', columns: ['uploaded_at'] },
  { name: 'idx_recurring_schedules_status_next', table: 'recurring_schedules', columns: ['status', 'next_run_at'] },
  { name: 'idx_recurring_schedules_account', table: 'recurring_schedules', columns: ['account_slot', 'status'] },
  { name: 'idx_content_pool_schedule', table: 'content_pool', columns: ['recurring_schedule_id', 'used_count'] },
  { name: 'idx_automation_rules_enabled', table: 'automation_rules', columns: ['enabled', 'trigger_type', 'account_slot'] },
  { name: 'idx_automation_rule_runs_rule', table: 'automation_rule_runs', columns: ['rule_id', 'created_at'] },
  { name: 'idx_feeds_status_checked', table: 'feeds', columns: ['status', 'last_checked_at'] },
  { name: 'idx_feed_entries_unique', table: 'feed_entries', columns: ['feed_id', 'entry_url'], unique: true },
  { name: 'idx_feed_entries_feed_created', table: 'feed_entries', columns: ['feed_id', 'created_at'] },
  { name: 'idx_saved_searches_status_checked', table: 'saved_searches', columns: ['status', 'last_checked_at'] },
  { name: 'idx_saved_search_matches_unique', table: 'saved_search_matches', columns: ['search_id', 'match_id'], unique: true },
  { name: 'idx_saved_search_matches_search_created', table: 'saved_search_matches', columns: ['search_id', 'created_at'] },
  { name: 'idx_short_urls_code', table: 'short_urls', columns: ['short_code'], unique: true },
  { name: 'idx_short_urls_post', table: 'short_urls', columns: ['post_id'] },
  { name: 'idx_url_clicks_short_url', table: 'url_clicks', columns: ['short_url_id', 'clicked_at'] },
  { name: 'idx_follower_snapshots_slot_time', table: 'follower_snapshots', columns: ['account_slot', 'snapshot_at'] },
  { name: 'idx_post_approvals_post', table: 'post_approvals', columns: ['post_id'] },
  { name: 'idx_post_approvals_status', table: 'post_approvals', columns: ['status'] },
];
